from: gfm+tex_math_gfm
to: html5
standalone: true
include-before-body: header/header.html
include-after-body: header/contact.html
template: default.html
html-math-method:
  method: mathml
toc: false
resource-path: [".", "${.}/header"]
